### ISSUE TITLE
add support for new docType "addenda"

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#240]
i.e. addenda & corrigenda pages for the printed volumes. To be located under `projects/Contents_of_Series_and_Volumes`

## todos

- [x] create object in wdt.xqm
- [x] add and update functions in config.xqm
- [x] create  controller rule for addenda underneath  "Contents_of_Series_and_Volumes"
- [x] replace ID A070011 with proper string "Contents_of_Series_and_Volumes"  in breadcrumb
- [x] adjust HTML metadata section(?)
- [ ] check popover
- [x] create icon
- [x] add entries to sitemap
- [x] (add to and) check search

**Comment by peterstadler** [comment]
suffices for now …
NB: There is no popover because we do not show previews but link directly to the addenda pages
